### ISSUE TITLE
Error in compiling the code

### ISSUE THREAD

**Issue by sudiptamandal** [dcherrera/Julian-Ilett-Arduino-MPPT-SCC#1]
I tried compiling the code and the error was with the header file. Please help me to solve this issue
![error](https://user-images.githubusercontent.com/12246139/39922796-759ccf5a-553e-11e8-9d4e-e52801fb063b.jpg)

**Comment by dcherrera** [comment]
is the header.h file in the same folder?

**Comment by dcherrera** [comment]
also I just found and placed the code here so I could easily find it when i get around to building it. all this code is so scattered across the inter-webs that its easier to upload all future interesting code to github.

**Comment by sudiptamandal** [comment]
Now the compiling error has been solved but now there is something wrong with the header file. After #include there should be a file name.



![error2](https://user-images.githubusercontent.com/12246139/39937311-f5fdc306-556c-11e8-9e5c-88fa05c6e45f.jpg)

![error1](https://user-images.githubusercontent.com/12246139/39931100-0c78ba36-555a-11e8-87ff-1c5c8622cdd5.jpg)

**Comment by dcherrera** [comment]
Opps. Remove "#include"

**Comment by dcherrera** [comment]
I fixed the code. you can pull down the new code. let me know if it works.

**Comment by dcherrera** [comment]
Also be sure to change the pin out code for whatever screen you are using or it wont work.

**Comment by sudiptamandal** [comment]
well the code works fine. Thanks Sir :)

**Comment by dcherrera** [comment]
cool
